language: go

go:
    - 1.12

env:
    global:
        - TZ=Asia/Tokyo
        - GO111MODULE=on
        - secure: "Kt1ybTvi0s8BtV3FOgwAuiQ7pLTQQ9+Vuj7D0tJijRpzLl0W9vZXH9qzis2VHBSktOsK+CVxkawWyT+/uBMopzrydMQj0csL5tYteqcvUkX3jGMPZ0ygJf6SEHRST53Ej27F0Mr0pykYHimkhoQQ9WlvUGXDtubuUkFJ41n2fnCRjfUGpuIkIuNiuVxrMzV4xIo1nWli5VTIvybl+pplHQ1Grbs7tcKn8ok1c1TMoDqaV85l/Cl+GPLV4coR6Nd/3hNv/w9/CkGS9bqYa/imAIInkzEeHXU/KvT97xkAzUSRSYhnxWMx2G7MC6hOfWr75xcBxWpIDdss5qKXIIrqcUfALmMSzl1byPJWouRVaROVBMHI4fUQ9diKSTmZlmCzau1nQ2Zw0DXce4cowwlilBKwW0FDOLrsOevLNtCZ9cjLnhngxbHyg18eSHcCcs3xfPnw82Y/5TgljMl+rtdhO63D+PoHtOAJcwAX/lSVD5JpHir5WX75ynDW9+VXRnfhGIe3F5LndsS+N0Ar6OI3NEfLy0MqWB/Zts4lP3K5mkl9h3aghEFbdTjs8A2Vs3Gbi1Hs3RhCBiovG+wOvXB1zTlUNH7mRTU5Z9nnGsgYA6wH+yrwSKhZLVrXXmFm+i0X6ew4oO5n4ahJvfVWCaaP8oiRzrPQz/rNSXRxKcX1RS4="

before_script:
    - go get github.com/mattn/goveralls

script:
    - make test build
    - $GOPATH/bin/goveralls.go -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
