baseURL = "https://tamada.github.io/rrh"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "rrh"
theme = "cayman-hugo-theme"
enableEmoji = true
googleAnalytics = "UA-62401730-6"

pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
    project_name = "rrh"
    project_tagline = "A simple git repository manager"
    project_logo = "images/logo.png"
    dateFormat = "2006-01-02"

    footer = "[![GitHub](https://img.shields.io/badge/GitHub-tamada/rrh-blueviolet.svg?logo=github)](https://github.com/tamada/rrh) Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."

    katex = true

[menu]
  [[menu.nav]]
    name = ":house: Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = ":bookmark_tabs: Description"
    url = "/description/"
    weight = 2
  [[menu.nav]]
    name = ":anchor: Installation"
    url = "/installation/"
    weight = 3
  [[menu.nav]]
    name = ":fork_and_knife: Usage"
    url = "/usage/"
    weight = 4
  [[menu.nav]]
    name = ":pencil2: Development"
    url = "/development/"
    weight = 5
  [[menu.nav]]
    name = ":electric_plug: Utilities"
    url = "/utilities/"
    weight = 6
  [[menu.nav]]
    name = ":smile: About"
    url = "/about/"
    weight = 7
