name: build
on:
    push:
        branches:
            - "**"
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macOS-latest
                    - windows-latest
        steps:
            - name: setup go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - name: checkout
              uses: actions/checkout@v1
            - name: build
              run: make
            - name: Convert coverage to lcov
              uses: jandelgado/gcov2lcov-action@v1.0.0
              with:
                  infile: coverage.out
                  outfile: coverage.lcov
              if: "matrix.os == 'ubuntu-latest'"
            - name: coveralls
              uses: coverallsapp/github-action@v1.0.1
              with:
                  github-token: ${{ secrets.github_token }}
                  path-to-lcov: coverage.lcov
              if: "matrix.os == 'ubuntu-latest'"
