name: Version Up
on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]*'

jobs:
  versionup:
    runs-on: ubuntu-latest
    steps:
      - name: Get branches
        run: |
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo "::set-output name=tag::${GITHUB_REF##**/v}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.branch }}
          fetch-depth: 0

      - name: Initialize
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
 
      - name: Version up
        id: updating_version
        run:
          (bash ./.bin/update_version.sh ${{ steps.vars.outputs.tag }} update_version && git commit -a -m "update version to ${{ steps.vars.outputs.tag }}, ready to publish v${{ steps.vars.outputs.tag }}") || true

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.vars.outputs.branch }}